package forum;


/**
* forum/ForumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 04 CET
*/

public interface ForumOperations 
{
  String theme ();
  String moderator ();
  boolean postMessage (forum.Message m);
  forum.Message getMessage (String title);
  boolean removeMessage (String title);
  forum.Message[] messageList ();
} // interface ForumOperations
