package forum;


/**
* forum/MessageSetHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 04 CET
*/

abstract public class MessageSetHelper
{
  private static String  _id = "IDL:forum/MessageSet:1.0";

  public static void insert (org.omg.CORBA.Any a, forum.Message[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static forum.Message[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = forum.MessageHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (forum.MessageSetHelper.id (), "MessageSet", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static forum.Message[] read (org.omg.CORBA.portable.InputStream istream)
  {
    forum.Message value[] = null;
    int _len0 = istream.read_long ();
    value = new forum.Message[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = forum.MessageHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, forum.Message[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      forum.MessageHelper.write (ostream, value[_i0]);
  }

}
