package forum;

/**
* forum/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 04 CET
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public forum.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (forum.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = forum.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    forum.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return forum.MessageHelper.type ();
  }

}
