package forum;


/**
* forum/ForumAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public interface ForumAdminOperations 
{
  String theme ();
  void theme (String newTheme);
  String moderator ();
  void moderator (String newModerator);
} // interface ForumAdminOperations
