package forum;


/**
* forum/ForumPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public class ForumPOATie extends ForumPOA
{

  // Constructors

  public ForumPOATie ( forum.ForumOperations delegate ) {
      this._impl = delegate;
  }
  public ForumPOATie ( forum.ForumOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public forum.ForumOperations _delegate() {
      return this._impl;
  }
  public void _delegate (forum.ForumOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String theme ()
  {
    return _impl.theme();
  } // theme

  public String moderator ()
  {
    return _impl.moderator();
  } // moderator

  public boolean postMessage (forum.Message m) throws forum.Reject
  {
    return _impl.postMessage(m);
  } // postMessage

  public forum.Message getMessage (String title)
  {
    return _impl.getMessage(title);
  } // getMessage

  public boolean removeMessage (String title) throws forum.Reject
  {
    return _impl.removeMessage(title);
  } // removeMessage

  public forum.Message[] messageList ()
  {
    return _impl.messageList();
  } // messageList

  public void getInfo (org.omg.CORBA.StringHolder theme, org.omg.CORBA.StringHolder moderator, org.omg.CORBA.IntHolder size)
  {
    _impl.getInfo(theme, moderator, size);
  } // getInfo

  private forum.ForumOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ForumPOATie
