package forum;

/**
* forum/ForumAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public final class ForumAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public forum.ForumAdmin value = null;

  public ForumAdminHolder ()
  {
  }

  public ForumAdminHolder (forum.ForumAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = forum.ForumAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    forum.ForumAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return forum.ForumAdminHelper.type ();
  }

}
