package forum;


/**
* forum/ForumPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public abstract class ForumPOA extends org.omg.PortableServer.Servant
 implements forum.ForumOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_theme", new java.lang.Integer (0));
    _methods.put ("_get_moderator", new java.lang.Integer (1));
    _methods.put ("postMessage", new java.lang.Integer (2));
    _methods.put ("getMessage", new java.lang.Integer (3));
    _methods.put ("removeMessage", new java.lang.Integer (4));
    _methods.put ("messageList", new java.lang.Integer (5));
    _methods.put ("getInfo", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // forum/Forum/_get_theme
       {
         String $result = null;
         $result = this.theme ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // forum/Forum/_get_moderator
       {
         String $result = null;
         $result = this.moderator ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // forum/Forum/postMessage
       {
         try {
           forum.Message m = forum.MessageHelper.read (in);
           boolean $result = false;
           $result = this.postMessage (m);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (forum.Reject $ex) {
           out = $rh.createExceptionReply ();
           forum.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // forum/Forum/getMessage
       {
         String title = in.read_string ();
         forum.Message $result = null;
         $result = this.getMessage (title);
         out = $rh.createReply();
         forum.MessageHelper.write (out, $result);
         break;
       }

       case 4:  // forum/Forum/removeMessage
       {
         try {
           String title = in.read_string ();
           boolean $result = false;
           $result = this.removeMessage (title);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (forum.Reject $ex) {
           out = $rh.createExceptionReply ();
           forum.RejectHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // forum/Forum/messageList
       {
         forum.Message $result[] = null;
         $result = this.messageList ();
         out = $rh.createReply();
         forum.MessageSetHelper.write (out, $result);
         break;
       }

       case 6:  // forum/Forum/getInfo
       {
         org.omg.CORBA.StringHolder theme = new org.omg.CORBA.StringHolder ();
         org.omg.CORBA.StringHolder moderator = new org.omg.CORBA.StringHolder ();
         org.omg.CORBA.IntHolder size = new org.omg.CORBA.IntHolder ();
         this.getInfo (theme, moderator, size);
         out = $rh.createReply();
         out.write_string (theme.value);
         out.write_string (moderator.value);
         out.write_long (size.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:forum/Forum:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Forum _this() 
  {
    return ForumHelper.narrow(
    super._this_object());
  }

  public Forum _this(org.omg.CORBA.ORB orb) 
  {
    return ForumHelper.narrow(
    super._this_object(orb));
  }


} // class ForumPOA
