package forum;


/**
* forum/ForumAdminPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public class ForumAdminPOATie extends ForumAdminPOA
{

  // Constructors

  public ForumAdminPOATie ( forum.ForumAdminOperations delegate ) {
      this._impl = delegate;
  }
  public ForumAdminPOATie ( forum.ForumAdminOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public forum.ForumAdminOperations _delegate() {
      return this._impl;
  }
  public void _delegate (forum.ForumAdminOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String theme ()
  {
    return _impl.theme();
  } // theme
  public void theme (String newTheme)
  {
    _impl.theme(newTheme);
  } // theme

  public String moderator ()
  {
    return _impl.moderator();
  } // moderator
  public void moderator (String newModerator)
  {
    _impl.moderator(newModerator);
  } // moderator

  private forum.ForumAdminOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ForumAdminPOATie
