package forum;


/**
* forum/ForumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public interface ForumOperations 
{
  String theme ();
  String moderator ();
  boolean postMessage (forum.Message m) throws forum.Reject;
  forum.Message getMessage (String title);
  boolean removeMessage (String title) throws forum.Reject;
  forum.Message[] messageList ();
  void getInfo (org.omg.CORBA.StringHolder theme, org.omg.CORBA.StringHolder moderator, org.omg.CORBA.IntHolder size);
} // interface ForumOperations
