package forum;


/**
* forum/MessageSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public final class MessageSetHolder implements org.omg.CORBA.portable.Streamable
{
  public forum.Message value[] = null;

  public MessageSetHolder ()
  {
  }

  public MessageSetHolder (forum.Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = forum.MessageSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    forum.MessageSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return forum.MessageSetHelper.type ();
  }

}
