package forum;

/**
* forum/RejectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Documents/Florian/fac/M2/appRep/Tp1/forum.idl
* jeudi 13 novembre 2014 12 h 49 CET
*/

public final class RejectHolder implements org.omg.CORBA.portable.Streamable
{
  public forum.Reject value = null;

  public RejectHolder ()
  {
  }

  public RejectHolder (forum.Reject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = forum.RejectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    forum.RejectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return forum.RejectHelper.type ();
  }

}
